### ISSUE TITLE
Using WebDAVClient.Client BasePath

### ISSUE THREAD

**Issue by andy-w** [saguiitay/WebDAVClient#2]
Not sure what is meant to happen here, but if I set the BasePath to "/remote.php/webdav". Then using folder.Href gives a path that includes the base path. So if this is then used in Get/List etc the base path is again added to the path being used so becomes "/remote.php/webdav/remote.php/webdav"

**Comment by saguiitay** [comment]
Resolved with commit b5795e7697417e7852975a57175def3c38925c23 and NuGet v1.0.9
