### ISSUE TITLE
is WebDavClient supported into ASP.NET Core 2 App?

### ISSUE THREAD

**Issue by parejajd** [saguiitay/WebDAVClient#27]
I am try use WebDavClient into ASP.NET Core 2 App, but i get this error calling List Method

Could not load type 'System.Web.HttpException' from assembly 'System.Web, Version=4.0.0.0'

is already compatible con ASP.NET Core 2?

**Comment by saguiitay** [comment]
It doesn't support .Net Core yet. I'm planning to add support for it when I get a chance, but that might take a while. Feel free to send me a PR if your up to it.

**Comment by lyze237** [comment]
I've done the support for .net standard and therefore it should work in .net and .net core: #34
