### ISSUE TITLE
Delete file/directory feature missing?

### ISSUE THREAD

**Issue by grishin** [saguiitay/WebDAVClient#4]

**Comment by saguiitay** [comment]
When I first implemented the library, I didn't require the Delete functionality, so I didn't implement it.
You are free to send me a PR, or you can wait until I implement it (might take a bit of time)

**Comment by saguiitay** [comment]
Added DeleteFolder and DeleteFile in commit 8fd04c650db287fc7c2578a27630eff7c3084a40 (included in NuGet package version 1.0.17).
Notice that this might not work in all WebDAV services - for example, http://www.4shared.com return 200 OK on delete requests, but the items are not actually deleted.
