### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by andy-w** [saguiitay/WebDAVClient#7]
I was having trouble with my SSL certificate for my owner https server as it was self signed (no root authority), adding this to the test program helped me figure out the problem. Just wondered if might me useful to add.

using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System;

namespace TestWebDAVClient
{
    class Program
    {
      ...

        private static bool ValidateCertificate(
            object sender,
            X509Certificate certificate,
            X509Chain chain,
            SslPolicyErrors sslPolicyErrors)
        {
            Console.WriteLine("Issued by: " + certificate.Issuer);
            Console.WriteLine("Issued to: " + certificate.Subject);
            Console.WriteLine("Valid until: " + certificate.GetExpirationDateString());

            if (sslPolicyErrors == SslPolicyErrors.None)
                Console.WriteLine("Valid server certificate");

            return true;
        }
        private static async Task MainAsync()
        {
            ServicePointManager.ServerCertificateValidationCallback = new RemoteCertificateValidationCallback(ValidateCertificate);

            // Basic authentication required
    ...

**Comment by saguiitay** [comment]
This is definitely useful, but I don't think it should be part of the library itself.
I've added it as a wiki page: https://github.com/saguiitay/WebDAVClient/wiki/Working-with-SSL-Certificates
